### ISSUE TITLE
error "KeyError: '_module'"  when running gdrive_upload.py

### ISSUE THREAD

**Issue by sputnick-dev** [kshcherban/gdrive_uploader#1]
I use the same exact test as your README : 

```
% ./gdrive_upload.py test.txt 
Traceback (most recent call last):
  File "./gdrive_upload.py", line 121, in <module>
    http = authorize(token_file, None)
  File "./gdrive_upload.py", line 65, in authorize
    credentials = storage.get()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 396, in get
    return self.locked_get()
  File "/usr/lib/python2.7/site-packages/oauth2client/file.py", line 81, in locked_get
    credentials = Credentials.new_from_json(content)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 301, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```

google-api-python-client (1.4.2)
python 2.7.11

API client id and secret + client_secret.json verified OK

**Comment by kshcherban** [comment]
Works with google-api-python-client (1.4.2) and python 2.7.9 on my Debian 8 laptop and python-googleapi (1.4.1-1) and python 2.7.11 on my local server with Ubuntu 16.04.
Seems like your local issue with oauth2client

```
Setting up python-googleapi (1.4.1-1) ...
[11:42]root@insider-pc:~# python --version
Python 2.7.11
[11:43]insider@insider-pc:~$ echo test > test.txt
[11:43]insider@insider-pc:~$ ./gdrive_upload.py test.txt 
Go to the following link in your browser: https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=xxx.apps.googleusercontent.com&access_type=offline
Enter verification code: 4/oRN8pZExxxxx
https://docs.google.com/uc?id=0B2HAYWY0hlIhNUY4SmRXVmdJR0U&export=download
[11:43]insider@insider-pc:~$ wget -q -O - "https://docs.google.com/uc?id=0B2HAYWY0hlIhNUY4SmRXVmdJR0U&export=download"
test
```

**Comment by sputnick-dev** [comment]
If someone have the same issue : `auth_token.txt` and  `client_secret.json` are not the same ! Don't link the `client_secret.json` from google API console. The file will be automatically created by the script.

**Comment by alegomes** [comment]
Same happened to me. The problem was I was using Python 3.5.0. So, I started using google-api-python-client-py3 instead of google-api-python-client. Then, I got "NameError: name 'raw_input' is not defined" and it was just a matter of changing the source code (line 53) from raw_input() to input(), according to http://docs.python.org/dev/py3k/whatsnew/3.0.html. Now, it's working.

**Comment by davesdere** [comment]
I tried with Python 3.5 and Python 2.7 on Raspbian Stretch and I got no luck.
I followed the guide to get the creds.  I modified the script accordingly.

```
token_file = sys.path[0] + '/client_secrets.json'

# Copy your credentials from the APIs Console
CLIENT_ID = '000000000000000000000000000000n.apps.googleusercontent.com'
CLIENT_SECRET = 'ThisIsASecret'
# Check https://developers.google.com/drive/scopes for all available scopes
OAUTH_SCOPE = 'https://www.googleapis.com/auth/drive.file'
# Redirect URI for installed apps, can be left as is
REDIRECT_URI = 'urn:ietf:wg:oauth:2.0:oob'

```
`python gdrive_uploader.py test.txt`

```
`Traceback` (most recent call last):
  File "gdrive_upload.py", line 120, in <module>
    http = authorize(token_file, None)
  File "gdrive_upload.py", line 64, in authorize
    credentials = storage.get()
  File "/home/pi/.local/lib/python2.7/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/home/pi/.local/lib/python2.7/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/home/pi/.local/lib/python2.7/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: `'_module'`

```
and with python3
```
Traceback (most recent call last):
  File "gdrive_upload.py", line 120, in <module>
    http = authorize(token_file, None)
  File "gdrive_upload.py", line 64, in authorize
    credentials = storage.get()
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

```
Any pointers anyone?

**Comment by akrv** [comment]
the exact same issue as @davesdere

**Comment by KeithEMoore** [comment]
I was having this problem and then realized I was pointing to a credentials file I had generated with an older version of the Google API.  The older version only included the access_token, refresh_token and expiry_date.

The newer version includes several objects that add more information about the credentials, including _module which defines which authorization module should be used with the credentials file.

The end of your credentials.json should include these parts (set properly for your request):

"scopes": ["https://www.googleapis.com/auth/gmail.modify", "https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/gmail.send"], "token_info_uri": "https://www.googleapis.com/oauth2/v3/tokeninfo", "invalid": false, "_class": "OAuth2Credentials", "_module": "oauth2client.client"}

Unfortunately the error checking is very sloppy so instead of detecting an incomplete credential file and throwing a useful error all you get is KeyError: '_module'

Edit (for clarity):  If your JSON doesn't include those parts you should regenerate a new one through the normal authorization process.

**Comment by max326-coder** [comment]
i have also a same problem help me out 

PS C:\Users\Dhaval\Downloads\uds-master> python3 uds.py push ~\Desktop\ffmpeg.exe
Traceback (most recent call last):
  File "uds.py", line 534, in <module>
    main()
  File "uds.py", line 452, in main
    uds = UDS()
  File "uds.py", line 46, in __init__
    self.api = GoogleAPI()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 19, in __init__
    self.reauth()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 25, in reauth
    credentials = store.get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
**KeyError: '_module'**

**Comment by kshcherban** [comment]
@max326-coder please check comment above, maybe you have outdated credentials file.

**Comment by kshcherban** [comment]
Also [oauth2client](https://github.com/googleapis/oauth2client) is deprecated, i need to rewrite code to use new libraries.

**Comment by micjgam** [comment]
So... I just went through this rigamarole as well with GCP. In the end, I was able to generate the credentials.json file and the subsequent token.json.

However, now I am getting a KeyError: '_module' error when calling ezgmail.init(). I have the prerequisite modules and files already. All solutions say to delete the token.json file and rerun the authorization process, but this does not work.

Here is the traceback:

      File "<stdin>", line 1, in <module>
      File "c:\Installs\Python\lib\site-packages\ezgmail\__init__.py", line 471, in init
         creds = store.get()
      File "c:\Installs\Python\lib\site-packages\oauth2client\client.py", line 407, in get
         return self.locked_get()
      File "c:\Installs\Python\lib\site-packages\oauth2client\file.py", line 54, in locked_get
         credentials = client.Credentials.new_from_json(content)
      File "c:\Installs\Python\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
         module_name = data['_module']
     KeyError: '_module'

*** UPDATE ***

I changed a line in the ezgmail/init.py file (line 471) from:

      creds = store.get()
to:

     creds = None
Immediately upon running

     import ezgmail
apparently a new token.json file is written. I then reverted the ezgmail/init.py file (line 471) back to...

     creds = store.get()
... and now I can run ezgmail.init() with no issues!

This represents my limited knowledge of python and I am only just beginning, so please bear with my explanation above.  I aim to try and explain as best as I can how I found a solution so that someone can possibly walk away with an answer as to why a solution works rather than just "it works" and I can move on.

**Comment by kshcherban** [comment]
> So... I just went through this rigamarole as well with GCP. In the end, I was able to generate the credentials.json file and the subsequent token.json.
> 
> However, now I am getting a KeyError: '_module' error when calling ezgmail.init(). I have the prerequisite modules and files already. All solutions say to delete the token.json file and rerun the authorization process, but this does not work.
> 
> Here is the traceback:
> 
> ```
>   File "<stdin>", line 1, in <module>
>   File "c:\Installs\Python\lib\site-packages\ezgmail\__init__.py", line 471, in init
>      creds = store.get()
>   File "c:\Installs\Python\lib\site-packages\oauth2client\client.py", line 407, in get
>      return self.locked_get()
>   File "c:\Installs\Python\lib\site-packages\oauth2client\file.py", line 54, in locked_get
>      credentials = client.Credentials.new_from_json(content)
>   File "c:\Installs\Python\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
>      module_name = data['_module']
>  KeyError: '_module'
> ```
> 
> *** UPDATE ***
> 
> I changed a line in the ezgmail/init.py file (line 471) from:
> 
> ```
>   creds = store.get()
> ```
> 
> to:
> 
> ```
>  creds = None
> ```
> 
> Immediately upon running
> 
> ```
>  import ezgmail
> ```
> 
> apparently a new token.json file is written. I then reverted the ezgmail/init.py file (line 471) back to...
> 
> ```
>  creds = store.get()
> ```
> 
> ... and now I can run ezgmail.init() with no issues!
> 
> This represents my limited knowledge of python and I am only just beginning, so please bear with my explanation above. I aim to try and explain as best as I can how I found a solution so that someone can possibly walk away with an answer as to why a solution works rather than just "it works" and I can move on.

@micjgam thanks for reporting, new code shouldn't use `oauth2client` anymore, please try with latest master commit.

**Comment by wescpy** [comment]
Ok, **now** I've figured out the root cause of this issue: there's code that uses "the old stuff," (`oauth2client`), web or CLI), that's conflicting with another piece of code using "the new stuff," (`google.oauth2`) where developers have to manage their own token storage (whereas in the old stuff, the `Storage` class took care of it). The old stuff relies on `_class` and `_module` JSON entries in the token storage file, but the new stuff doesn't care nor write that stuff out. If you're still running into this problem, either stay on the old stuff or go cold turkey and move everything to the new stuff. The old stuff still works as long as you don't "mix-n-match" with the new stuff. I'll update this comment when I've documented this well enough or have come up with a solution.
